# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T6txdUVA2b_d74QT7XqrOnkUcLHs22oJ
"""

import pandas as pd
import numpy as np
np.append
from sklearn.metrics.pairwise import cosine_similarity
from sklearn. feature_extraction.text import CountVectorizer

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('book_reviews123.csv', encoding='unicode_escape', error_bad_lines=False)

columns = ['book', 'review', 'state']

df['book'][1]

df['title']=range(0,2000)

df

def combineF(data):
  features = []
  for i in range(0, data.shape[0]):
    features.append(str(data['book'][i]) + ' ' + str(data['review'][i]) + ' ' + str(data['state'][i]))
  return features

df['combinedF'] = combineF(df)
df

cm = CountVectorizer().fit_transform(df['combinedF'])

cs = cosine_similarity(cm)
print(cs)

cs.shape

Book_title = df[df.book == book]['title'].values
Book_title

Book = df['book'][1]
Book

df[df.book == Book]

title =input("Please enter title")

scores=list(enumerate(cs[Book_title]))
print(scores)

sorted_scores = sorted(scores, key = lambda x:x[1].all(), reverse = True)
sorted_scores = sorted_scores[1:]

print(sorted_scores)

j=0
print('The most recommended books', title, 'are:\n')
for item in sorted_scores:
  book_title = df[df.title == item[0]]['book'].values[0]
  print(j+1, book_title)
  j = j+1
  if j>6:
    break